### ISSUE TITLE
Accessibility improvements for top navigation

### ISSUE THREAD

**Issue by CR96** [CityOfDetroit/ddot-info#88]
#### Description:
Add `aria-label` attributes to navigation links for screen reader users.
Also add `aria-label` attribute to "DDOT" navigation link for proper pronunciation.

**Comment by maxatdetroit** [comment]
After discussion with @CR96 on #89 and #91 as well as some A11Y testing in Firefox, we were able to confirm that the top nav links have sufficient context for assistive devices.

Closing this out.
